name: SQRankup
main: com.regalphoenixmc.SQRankup.SQRankup
version: 1.7.3
softdepend: [PermissionsEx]
depend: [Vault]
commands:
  rankup:
    description: Rank up!
    usage: /rankup
  addapp:
    description: Mark a player as applied.
    usage: /addapp <Player>
  rankuprefresh:
    description: Refresh Rankup Multiplier
  rankupmultiplier:
    description: Set a kill multiplier
    usage: /rankupmultiplier <int>
  perkadd:
    description: Add a perk to a player 
    usage: /perkadd <string alias>
  perkredeem:
    description: Redeem a perk from your queue
    usage: /perkredeem | /perkredeem <alias>
  perktrade:
    description: Create an offer for a perk
    usage: /perktrade <want> <have> <hour expiry> <player (Optional)> || /perktrade <id>
    
   